const products = [
  {
    name: "Chocolate Roll",
    price: "Rp 99.000",
    description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit.",
    image: "image/product/thumb/chocolate-roll.jpg",
    fullImage: "image/product/chocolate-roll.jpg",
    link: "detail.html?product=chocolate-roll",
    category: "Cakes",
  },
  {
    name: "Brownies",
    price: "Rp 99.000",
    description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit.",
    image: "image/product/thumb/brownies.jpg",
    fullImage: "image/product/brownies.jpg",
    link: "detail.html?product=brownies",
    category: "Cakes",
  },
  {
    name: "Milk Bread",
    price: "Rp 99.000",
    description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit.",
    image: "image/product/thumb/milk-bread.jpg",
    fullImage: "image/product/milk-bread.jpg",
    link: "detail.html?product=milk-bread",
    category: "Breads",
  },
  {
    name: "Chocolate Muffins",
    price: "Rp 99.000",
    description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit.",
    image: "image/product/thumb/muffin.jpg",
    fullImage: "image/product/muffins.jpg",
    link: "detail.html?product=muffins",
    category: "Pastries",
  },
  {
    name: "Honey Pancake",
    price: "Rp 99.000",
    description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit.",
    image: "image/product/thumb/honey-pancake.jpg",
    fullImage: "image/product/honey-pancake.jpg",
    link: "detail.html?product=honey-pancake",
    category: "Pastries",
  },
  {
    name: "Ginger Bread",
    price: "Rp 99.000",
    description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit.",
    image: "image/product/thumb/ginger-gread.jpg",
    fullImage: "image/product/gingerbread.jpg",
    link: "detail.html?product=ginger-bread",
    category: "Seasonal Specials",
  },
];

export default products;
